import React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Stats={users:number;posts:number;pending:number;moderation:number};
type ReportItem={id:string;reason:string;details:string|null;createdAt:string;post:{id:string;title:string};reporter:{firstName:string|null;username:string|null;telegramId:string}};
type QueueItem={id:string;title:string|null;body:string|null;category:string|null;moderationJson:string|null;createdAt:string;user:{firstName:string|null;username:string|null;telegramId:string}};
type Analytics={period:{days:number;since:string};overview:Record<string,number>;series:Array<{date:string;users:number;posts:number;views:number;reactions:number;comments:number;reports:number;moderation:number;xp:number}>;content:{categories:Array<{category:string;count:number}>;topCreators:Array<{id:string;firstName:string|null;username:string|null;_count:{posts:number;followers:number}}>} ;safety:{moderationByAction:Array<{action:string;count:number}>;reportsByReason:Array<{reason:string;count:number}>}};
type SafetyEvent={id:string;action:string;reason:string|null;createdAt:string;targetUser:{id:string;telegramId:string;username:string|null;firstName:string|null;blocked:boolean;restrictedUntil:string|null}|null;moderator:{id:string;username:string|null;firstName:string|null}|null};
type OppItem={id:string;title:string;description:string;organization:string;type:string;category:string;location:string|null;deadline:string|null;applicationUrl:string|null;verified:boolean;active:boolean;createdAt:string;owner:{id:string;firstName:string|null;username:string|null}|null;_count:{saves:number}};
type UserItem={id:string;telegramId:string;username:string|null;firstName:string|null;role:string;blocked:boolean;restrictedUntil:string|null;createdAt:string;xp:number;level:number;_count:{posts:number;followers:number;following:number;comments:number}};
const API=(import.meta.env.VITE_API_URL||"http://localhost:3000").replace(/\/+$/,"");
const labels:Record<string,string>={users:"👥 ተጠቃሚዎች",posts:"📝 ፖስቶች",communities:"🏘️ ማህበረሰቦች",communityMembers:"👨‍👩‍👧 አባላት",opportunities:"🚀 እድሎች",events:"🎉 ዝግጅቶች",polls:"🗳️ ምርጫዎች",quizzes:"🧠 ክዊዞች",views:"👁️ እይታዎች",reactions:"❤️ ምላሾች",comments:"💬 አስተያየቶች",openReports:"🚩 ክፍት ሪፖርቶች",moderationEvents:"🛡️ የሞዴሬሽን ክስተቶች",xpEvents:"⭐ XP ክስተቶች",eventRsvps:"🙋 RSVP",pollVotes:"🗳️ ድምጾች",quizAnswers:"🧠 መልሶች"};
function App(){
 const [key,setKey]=React.useState(localStorage.getItem("genzi_admin_key")??"");
 const [moderatorToken,setModeratorToken]=React.useState(localStorage.getItem("genzi_moderator_session")??"");
 const [moderatorLabel,setModeratorLabel]=React.useState(localStorage.getItem("genzi_moderator_label")??"");
 const [code,setCode]=React.useState("");
 const [stats,setStats]=React.useState<Stats|null>(null);const [analytics,setAnalytics]=React.useState<Analytics|null>(null);const [users,setUsers]=React.useState<UserItem[]>([]);const [queue,setQueue]=React.useState<QueueItem[]>([]);const [reports,setReports]=React.useState<ReportItem[]>([]);const [tab,setTab]=React.useState<"overview"|"analytics"|"safety"|"users"|"opportunities"|"content"|"confessions"|"messages"|"ask"|"settings">("overview");const [error,setError]=React.useState("");const [userQ,setUserQ]=React.useState("");const [settingDraft,setSettingDraft]=React.useState<Record<string,string>>({});
 const [safetyEvents,setSafetyEvents]=React.useState<SafetyEvent[]>([]);const [opps,setOpps]=React.useState<OppItem[]>([]);const [oppDraft,setOppDraft]=React.useState({title:"",description:"",organization:"",type:"JOB",category:"ስራ",applicationUrl:""});const [adminPosts,setAdminPosts]=React.useState<any[]>([]);const [postQ,setPostQ]=React.useState("");
 const [adminCommunities,setAdminCommunities]=React.useState<any[]>([]);
 const [adminConfessions,setAdminConfessions]=React.useState<any[]>([]);
 const [dmReports,setDmReports]=React.useState<any[]>([]);
 const [askQueue,setAskQueue]=React.useState<any[]>([]);
 const [askAnswers,setAskAnswers]=React.useState<Record<string,string>>({});
 const [settings,setSettings]=React.useState<Record<string,string>|null>(null);
 const headers=React.useMemo(()=>({"X-Admin-Key":key,...(moderatorToken?{"X-Moderator-Session":moderatorToken}:{})}),[key,moderatorToken]);
 const load=React.useCallback(async()=>{if(!key)return;setError("");try{const [a,b,c,d,e,f,g,h,i,j,k,l,m]=await Promise.all([fetch(`${API}/api/admin/stats`,{headers}),fetch(`${API}/api/admin/queue`,{headers}),fetch(`${API}/api/admin/reports`,{headers}),fetch(`${API}/api/admin/analytics?days=14`,{headers}),fetch(`${API}/api/admin/users?limit=50`,{headers}),fetch(`${API}/api/admin/safety/events?limit=50`,{headers}),fetch(`${API}/api/admin/opportunities?limit=50`,{headers}),fetch(`${API}/api/admin/posts?limit=50`,{headers}),fetch(`${API}/api/admin/communities?limit=50`,{headers}),fetch(`${API}/api/admin/confessions`,{headers}),fetch(`${API}/api/admin/dm-reports`,{headers}),fetch(`${API}/api/admin/ask`,{headers}),fetch(`${API}/api/admin/settings`,{headers})]);if([a,b,c,d,e].some(x=>!x.ok))throw new Error("የአስተዳደር መግቢያ አልተሳካም።");setStats((await a.json()).data);setQueue((await b.json()).data);setReports((await c.json()).data);setAnalytics((await d.json()).data);setUsers((await e.json()).data);setSafetyEvents(f.ok?(await f.json()).data??[]:[]);const gx=await g.json();setOpps(g.ok&&gx?.data?(gx.data.items??[]):[]);
   setAdminPosts(h.ok?(await h.json()).data??[]:[]);setAdminCommunities(i.ok?(await i.json()).data??[]:[]);setAdminConfessions(j.ok?(await j.json()).data??[]:[]);setDmReports(k.ok?(await k.json()).data??[]:[]);setAskQueue(l.ok?(await l.json()).data??[]:[]);const sx=m.ok?(await m.json()).data??null:null;setSettings(sx);if(sx)setSettingDraft(sx);localStorage.setItem("genzi_admin_key",key)}catch(e){setError(e instanceof Error?e.message:"ስህተት")}},[key,headers]);
 async function loadUserSearch(){if(!key)return;const r=await fetch(`${API}/api/admin/users?limit=50&q=${encodeURIComponent(userQ)}`,{headers});if(r.ok)setUsers((await r.json()).data??[]);else setError("ፍለጋ አልተሳካም።")}
 React.useEffect(()=>{void load()},[load]);
 async function post(path:string,body:unknown){const r=await fetch(`${API}${path}`,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setError(x.error??"ስህተት");return false}await load();return true}
 async function patch(path:string,body:unknown){const r=await fetch(`${API}${path}`,{method:"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setError(x.error??"ስህተት");return false}await load();return true}
 async function del(path:string){const r=await fetch(`${API}${path}`,{method:"DELETE",headers});const x=await r.json().catch(()=>null);if(!r.ok){setError(x?.error??"ስህተት");return false}await load();return true}
 async function put(path:string,body:unknown){const r=await fetch(`${API}${path}`,{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json().catch(()=>null);if(!r.ok){setError(x?.error??"ስህተት");return false}await load();return true}
 const OPP_TYPES=["JOB","GIG","INTERNSHIP","SCHOLARSHIP","TRAINING","COMPETITION","BUSINESS","OTHER"];const OPP_CATS=["ስራ","ፍሪላንስ","ትምህርት","ስኮላርሺፕ","ስልጠና","ውድድር","ንግድ","ሌላ"];
 async function verifyModerator(){setError("");try{const r=await fetch(`${API}/api/admin/moderator-session`,{method:"POST",headers:{"X-Admin-Key":key,"Content-Type":"application/json"},body:JSON.stringify({code})});const x=await r.json();if(!r.ok||!x.data){setError(x.error??"ኮድ ትክክል አይደለም።");return}const label=x.data.moderator.firstName??x.data.moderator.username??x.data.moderator.id;setModeratorToken(x.data.token);setModeratorLabel(label);setCode("");localStorage.setItem("genzi_moderator_session",x.data.token);localStorage.setItem("genzi_moderator_label",label)}catch(e){setError(e instanceof Error?e.message:"ስህተት")}}
 function logoutModerator(){setModeratorToken("");setModeratorLabel("");localStorage.removeItem("genzi_moderator_session");localStorage.removeItem("genzi_moderator_label")}
 return <main><header><div className="brand"><img src={`${import.meta.env.BASE_URL}genzi-icon-192.png`} alt="GENZI" className="brand-logo"/><div><h1>🛡️ GENZI አስተዳደር</h1><small>🇪🇹 ኦፕሬሽን · ትንታኔ · ደህንነት</small></div></div><button onClick={()=>void load()}>↻ አድስ</button></header>
 <section className="auth panel"><input value={key} onChange={e=>setKey(e.target.value)} placeholder="Admin API Key" type="password"/><button onClick={()=>void load()}>ግባ</button></section>
 <section className="auth panel">{moderatorToken?<><span>✅ ገብተዋል እንደ {moderatorLabel}</span><button onClick={logoutModerator}>ውጣ</button></>:<><input value={code} onChange={e=>setCode(e.target.value)} placeholder="ከቦቱ /moderatorlogin የተላከ ኮድ"/><button onClick={()=>void verifyModerator()}>🔐 አረጋግጥ</button></>}</section>
 {!moderatorToken&&<p className="muted">ሪፖርቶችን ለመዝጋት ወይም ይዘት ለማጽደቅ/ውድቅ ለማድረግ በመጀመሪያ ለቦቱ /moderatorlogin ይላኩ እና የተላከውን ኮድ እዚህ ያረጋግጡ።</p>}
 {error&&<div className="error" role="alert">⚠️ {error}</div>}
 <nav className="tabs" aria-label="የአስተዳደር ቅጽበቶች"><button aria-current={tab==="overview"?"page":undefined} className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>📌 አጠቃላይ</button><button aria-current={tab==="analytics"?"page":undefined} className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>📊 ትንታኔ</button><button aria-current={tab==="safety"?"page":undefined} className={tab==="safety"?"active":""} onClick={()=>setTab("safety")}>🛡️ ደህንነት</button><button aria-current={tab==="users"?"page":undefined} className={tab==="users"?"active":""} onClick={()=>setTab("users")}>👥 ተጠቃሚዎች</button><button aria-current={tab==="opportunities"?"page":undefined} className={tab==="opportunities"?"active":""} onClick={()=>setTab("opportunities")}>🚀 እድሎች</button><button aria-current={tab==="content"?"page":undefined} className={tab==="content"?"active":""} onClick={()=>setTab("content")}>📝 ይዘት</button><button aria-current={tab==="confessions"?"page":undefined} className={tab==="confessions"?"active":""} onClick={()=>setTab("confessions")}>🎭 መናዘዣዎች</button><button aria-current={tab==="messages"?"page":undefined} className={tab==="messages"?"active":""} onClick={()=>setTab("messages")}>💬 ሪፖርት DM</button><button aria-current={tab==="ask"?"page":undefined} className={tab==="ask"?"active":""} onClick={()=>setTab("ask")}>❓ ጥያቄዎች</button><button aria-current={tab==="settings"?"page":undefined} className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}>⚙️ ቅንብሮች</button></nav>
 {tab==="overview"&&<><section className="grid">{[["👥 ተጠቃሚዎች",stats?.users??"—"],["📝 ፖስቶች",stats?.posts??"—"],["⚠️ ግምገማ",stats?.pending??"—"],["🛡️ ሞዴሬሽን",stats?.moderation??"—"]].map(([a,b])=><article key={a}><b>{a}</b><strong>{b}</strong></article>)}</section><section className="panel"><h2>🚨 የሚጠብቁ ይዘቶች</h2>{queue.length===0?<p className="muted">የሚጠብቅ ይዘት የለም።</p>:queue.map(x=><article className="queue" key={x.id}><div><b>{x.title??"ያልተሰየመ"}</b><p>{x.body??""}</p><small>👤 {x.user.firstName??x.user.username??x.user.telegramId} · {x.category??"—"}</small></div><div className="actions"><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"APPROVE"})}>✅ አጽድቅ</button><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"REJECT"})}>⛔ አትቀበል</button><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"RESTRICT"})}>🔒 ገድብ</button><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"BAN"})}>🚫 አግድ</button></div></article>)}</section><section className="panel"><h2>🚩 የተጠቃሚ ሪፖርቶች</h2>{reports.length===0?<p className="muted">ክፍት ሪፖርት የለም።</p>:reports.map(r=><article className="queue" key={r.id}><div><b>{r.post.title}</b><p>ምክንያት: {r.reason}<br/>{r.details??""}</p></div><div className="actions"><button onClick={()=>void post(`/api/admin/reports/${r.id}/resolve`,{action:"DISMISS"})}>✓ ዝጋ</button><button onClick={()=>void post(`/api/admin/reports/${r.id}/resolve`,{action:"REMOVE"})}>🗑️ አስወግድ</button></div></article>)}</section></>}
 {tab==="analytics"&&analytics&&<><section className="grid">{Object.entries(analytics.overview).map(([k,v])=><article key={k}><b>{labels[k]??k}</b><strong>{v.toLocaleString()}</strong></article>)}</section><section className="panel"><h2>📈 የ14 ቀን እንቅስቃሴ</h2><div className="series">{analytics.series.map(x=><div key={x.date} className="day"><small>{x.date.slice(5)}</small><span style={{height:`${Math.min(100,Math.max(6,x.views+x.posts*5+x.reactions*3))}%`}}></span><b>{x.views}</b></div>)}</div></section><section className="split"><section className="panel"><h2>📚 የይዘት ምድቦች</h2>{analytics.content.categories.map(x=><p className="row" key={x.category}><span>{x.category}</span><b>{x.count}</b></p>)}</section><section className="panel"><h2>🌟 ከፍተኛ ፈጣሪዎች</h2>{analytics.content.topCreators.map(x=><p className="row" key={x.id}><span>{x.firstName??x.username??x.id}</span><b>{x._count.posts} posts</b></p>)}</section></section></>}
 {tab==="safety"&&analytics&&<><section className="split"><section className="panel"><h2>🛡️ የሞዴሬሽን እርምጃዎች</h2>{analytics.safety.moderationByAction.map(x=><p className="row" key={x.action}><span>{x.action}</span><b>{x.count}</b></p>)}</section><section className="panel"><h2>🚩 የሪፖርት ምክንያቶች</h2>{analytics.safety.reportsByReason.map(x=><p className="row" key={x.reason}><span>{x.reason}</span><b>{x.count}</b></p>)}</section></section><section className="panel"><h2>🧾 የደህንነት ክስተቶች ምዝገባ</h2>{safetyEvents.length===0?<p className="muted">ክስተት አልተመዘገበም።</p>:safetyEvents.map(({id,action,reason,createdAt,targetUser:tu,moderator})=>(<article className="user" key={id}><div><b>{action}</b><small>👤 {tu?(tu.firstName??tu.username??tu.telegramId):"—"} · {tu?.blocked?"🚫 ታግዷል":tu?.restrictedUntil?`⏳ ${new Date(tu.restrictedUntil).toLocaleString()}`:"✅ ንቁ"}</small><br/><small>🛡️ {moderator?(moderator.firstName??moderator.username??"አስተዳዳሪ"):"ስርዓት"} · {new Date(createdAt).toLocaleString()} · {reason??"—"}</small></div><div className="actions">{tu?.restrictedUntil&&!tu.blocked?<button onClick={()=>void post(`/api/admin/safety/users/${tu.id}/unrestrict`,{})}>🔓 ገደብ አስወግድ</button>:null}{tu?.blocked?<button onClick={()=>void post(`/api/admin/safety/users/${tu.id}/unban`,{})}>🔓 አንቃ</button>:null}</div></article>))}</section></>}
 {tab==="users"&&<section className="panel"><h2>👥 ተጠቃሚዎች</h2><div className="row"><input value={userQ} onChange={e=>setUserQ(e.target.value)} placeholder="🔎 ስም / username / telegram id ይፈልጉ" aria-label="ተጠቃሚ ፍለጋ"/><button onClick={()=>void loadUserSearch()}>ፈልግ</button></div>{users.length===0?<p className="muted">ተጠቃሚ አልተገኘም።</p>:users.map(u=><article className="user" key={u.id}><div><b>{u.firstName??u.username??u.telegramId}</b><small>{u.role} · Level {u.level} · {u.xp} XP · {u._count.posts} posts · {u._count.followers} followers</small></div><div className="actions">{u.blocked?<button onClick={()=>void post(`/api/admin/safety/users/${u.id}/unban`,{})}>🔓 አንቃ</button>:<><button onClick={()=>void post(`/api/admin/safety/users/${u.id}/restrict`,{hours:24})}>🔒 24ሰ ገድብ</button><button onClick={()=>{if(confirm(`${u.firstName??u.username??"ይህ"} በእውነት ይገደድ?`))void post(`/api/admin/safety/users/${u.id}/ban`,{reason:"admin panel ban"})}}>🚫 አግድ</button></>}{!u.blocked&&u.restrictedUntil?<button onClick={()=>void post(`/api/admin/safety/users/${u.id}/unrestrict`,{})}>🔓 ገደብ አስወግድ</button>:null}</div></article>)}</section>}
 {tab==="opportunities"&&<><section className="panel"><h2>➕ አዲስ እድል ፍጠር</h2><div className="form"><input value={oppDraft.title} onChange={e=>setOppDraft(d=>({...d,title:e.target.value}))} placeholder="ርዕስ *"/><input value={oppDraft.organization} onChange={e=>setOppDraft(d=>({...d,organization:e.target.value}))} placeholder="ድርጅት *"/><textarea value={oppDraft.description} onChange={e=>setOppDraft(d=>({...d,description:e.target.value}))} placeholder="መግለጫ *" rows={3}></textarea><input value={oppDraft.applicationUrl} onChange={e=>setOppDraft(d=>({...d,applicationUrl:e.target.value}))} placeholder="ማመልከቻ URL (https)"/><div className="row"><select value={oppDraft.type} onChange={e=>setOppDraft(d=>({...d,type:e.target.value}))}>{OPP_TYPES.map(t=><option key={t} value={t}>{t}</option>)}</select><select value={oppDraft.category} onChange={e=>setOppDraft(d=>({...d,category:e.target.value}))}>{OPP_CATS.map(c=><option key={c} value={c}>{c}</option>)}</select><button onClick={()=>{if(!oppDraft.title.trim()||!oppDraft.description.trim()||!oppDraft.organization.trim()){setError("ርዕስ፣ ድርጅት እና መግለጫ ያስፈልጋሉ።");return}void post("/api/admin/opportunities",oppDraft).then(ok=>{if(ok)setOppDraft({title:"",description:"",organization:"",type:"JOB",category:"ስራ",applicationUrl:""})})}}>💾 አስቀምጥ</button></div></div></section><section className="panel"><h2>🚀 የእድል ዝርዝር ({opps.length})</h2>{opps.length===0?<p className="muted">እድሎች የለም።</p>:opps.map(o=><article className="queue" key={o.id}><div><b>{o.title}</b><p>{o.description.slice(0,140)}{o.description.length>140?"…":""}</p><small>🏢 {o.organization} · {o.type} · {o.category}{o.location?` · 📍 ${o.location}`:""}{o.deadline?` · ⏰ ${new Date(o.deadline).toLocaleDateString()}`:""} · 🔖 {o._count.saves} · {o.owner?`👤 ${o.owner.firstName??o.owner.username??"—"}`:""}</small></div><div className="actions"><button onClick={()=>void patch(`/api/admin/opportunities/${o.id}`,{verified:!o.verified})}>{o.verified?"✔️ በረጋጠ":"❕ አረጋግጥ"}</button><button onClick={()=>void patch(`/api/admin/opportunities/${o.id}`,{active:!o.active})}>{o.active?"🙈 አደብቅ":"👁️ አሳይ"}</button></div></article>)}</section></>}
 {tab==="content"&&<><section className="panel"><h2>📝 ፖስቶች</h2><div className="row"><input value={postQ} onChange={e=>setPostQ(e.target.value)} placeholder="ርዕስ / ይዘት ይፈልጉ" aria-label="ፖስት ፍለጋ"/><button onClick={()=>{if(!key)return;void fetch(`${API}/api/admin/posts?limit=50&q=${encodeURIComponent(postQ)}`,{headers}).then(async r=>{if(r.ok)setAdminPosts((await r.json()).data??[]);else setError("ፍለጋ አልተሳካም።")})}}>ፈልግ</button></div>{adminPosts.length===0?<p className="muted">ፖስት አልተገኘም።</p>:adminPosts.map(p=><article className="queue" key={p.id}><div><b>{p.title??"ያልተሰየመ"}</b><small>👤 {p.authorName??"—"} · {p.category??"—"} · {p.visibility}{p.publishedAt?" · 🟢 published":" · ⚪ draft"} · 💬 {p._count.comments}</small></div><div className="actions">{p.visibility!=="DRAFT"?<button onClick={()=>{if(confirm("ይህን ፖስት ያስወግዱ?"))void post(`/api/admin/posts/${p.id}/remove`,{reason:"admin panel removal"})}}>🗑️ አስወግድ</button>:<span className="muted">ተወግዷል</span>}</div></article>)}</section><section className="panel"><h2>🏘️ ማህበረሰቦች ({adminCommunities.length})</h2>{adminCommunities.length===0?<p className="muted">ማህበረሰብ የለም።</p>:adminCommunities.map(c=><article className="queue" key={c.id}><div><b>{c.coverEmoji?`${c.coverEmoji} `:""}{c.name}</b><small>#{c.slug} · {c.category??"—"} · {c.isPublic?"🌐 ግልጽ":"🔒 ግላዊ"} · 👥 {c._count.members} · 📝 {c._count.posts}</small></div><div className="actions">{moderatorToken?<button onClick={()=>{if(confirm(`“${c.name}” ማህበረሰቡን ያስወግዱ?`))void post(`/api/admin/communities/${c.id}/remove`,{reason:"admin panel removal"})}}>🗑️ አስወግድ</button>:<span className="muted">ሞዴሬተር ያስፈልጋል</span>}</div></article>)}</section></>}
 {tab==="confessions"&&<section className="panel"><h2>🎭 ህዝባዊ መናዘዣዎች ({adminConfessions.length})</h2>{adminConfessions.length===0?<p className="muted">መናዘዣ የለም።</p>:adminConfessions.map(c=><article className="queue" key={c.id}><div><b>#{c.number} · {c.state}</b><p>{String(c.body).slice(0,220)}{String(c.body).length>220?"…":""}</p><small>🕒 {new Date(c.createdAt).toLocaleString()}</small></div><div className="actions">{moderatorToken?<>{(c.state==="QUARANTINED"||c.state==="PENDING")&&<button onClick={()=>{if(confirm("ይህን መናዘዣ ያጽድቁ እና ያትሙ?"))void post(`/api/admin/confessions/${c.id}/approve`,{})}}>✅ አጽድቅ</button>}<button onClick={()=>{if(confirm("ይህን መናዘዣ ያስወግዱ?"))void post(`/api/admin/confessions/${c.id}/remove`,{})}}>🗑️ አስወግድ</button></>:<span className="muted">ሞዴሬተር ያስፈልጋል</span>}</div></article>)}</section>}
 {tab==="messages"&&<section className="panel"><h2>💬 የተመዘገቡ DM ነገሮች ({dmReports.length})</h2>{dmReports.length===0?<p className="muted">ክፍት ሪፖርት የለም።</p>:dmReports.map(r=><article className="queue" key={r.id}><div><b>👤 {r.reported?.firstName??r.reported?.username??r.reported?.id??"—"} ← {r.reporter?.firstName??r.reporter?.username??"—"}</b><p>“{(r.message?.body??"—").slice(0,220)}”</p><small>🕒 {r.message?.createdAt?new Date(r.message.createdAt).toLocaleString():new Date(r.createdAt).toLocaleString()}</small></div><div className="actions">{moderatorToken?<><button onClick={()=>void post(`/api/admin/dm-reports/${r.id}/resolve`,{action:"DISMISS"})}>✓ ዝጋ</button><button onClick={()=>{if(confirm("የተመዘገበውን ተጠቃሚ ይገደድ?"))void post(`/api/admin/dm-reports/${r.id}/resolve`,{action:"BAN"})}}>🚫 አግድ</button></>:<span className="muted">ሞዴሬተር ያስፈልጋል</span>}</div></article>)}</section>}
 {tab==="ask"&&<section className="panel"><h2>❓ ለመመለስ የሚጠብቁ ጥያቄዎች ({askQueue.length})</h2>{askQueue.length===0?<p className="muted">ጥያቄ የለም።</p>:askQueue.map(q=><article className="queue" key={q.id}><div><b>{q.text}</b><small>👤 {q.anonymous?"አልያተሰየመ":`${q.author?.firstName??q.author?.username??""}`} · 🕒 {new Date(q.createdAt).toLocaleString()}</small><textarea rows={2} placeholder="መልስ ይጻፉ…" value={askAnswers[q.id]??""} onChange={e=>setAskAnswers(a=>({...a,[q.id]:e.target.value}))} aria-label="የጥያቄ መልስ"></textarea></div><div className="actions">{moderatorToken?<><button onClick={()=>{const t=(askAnswers[q.id]??"").trim();if(!t){setError("መልሱ ሊዛምድ አይችልም።");return}void post(`/api/admin/ask/${q.id}/answer`,{action:"ANSWER",answerBody:t}).then(ok=>{if(ok)setAskAnswers(a=>{const n={...a};delete n[q.id];return n})})}}>💬 መልስ</button><button onClick={()=>void post(`/api/admin/ask/${q.id}/answer`,{action:"REJECT"})}>⛔ ውድቅ</button></>:<span className="muted">ሞዴሬተር ያስፈልጋል</span>}</div></article>)}</section>}
 {tab==="settings"&&<section className="panel"><h2>⚙️ የስርዓት ቅንብሮች</h2>{!settings?<p className="muted">ቅንብሮች አልተጫኑም (አስተዳዳሪ ቁልፍ ያስፈልጋል)።</p>:<><div className="form">{Object.entries(settings).map(([k,v])=><div className="row" key={k}><label htmlFor={`setting-${k}`}>{k}</label><input id={`setting-${k}`} type="number" min={1} max={999999} value={settingDraft[k]??v} onChange={e=>setSettingDraft(d=>({...d,[k]:e.target.value}))}/></div>)}<button onClick={()=>void put("/api/admin/settings",settingDraft)}>💾 አስቀምጥ</button></div><p className="muted">እሴቶች አዎንታዊ ሙሉ ቁጥሮች ብቻ ናቸው። dm_recall_window_hours · earn_daily_limit · referral_reward_coins · subscription_grace_hours</p></>}</section>}
 </main>}
createRoot(document.getElementById("root")!).render(<App/>);
